name: For fun

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: say Hello
        run: echo "Hello World!"
      - name: get date
        run: date
      - name: list directory
        run: ls -la
